name: Deploy to magic branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to build-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.x.x
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
        env:
          CI: true
      - name: Build dist
        run: pnpm build
      - name: Cleanup folder structure
        run: rm -rf src prettier.config.js tsconfig.eslint.json tsconfig.json prettier.config.js pnpm-lock.yaml .eslintrc.js .prettierignore .gitignore .github
      - name: Run deploy script
        run: |
          git config user.name "PiJa Deploy" && git config user.email "it@pija.se"
          npm run deploy
